apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-image-deployment
  labels:
    app: sampleapp-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp-image
  template:
    metadata:
      labels:
        app: sampleapp-image
    spec:
      containers:
      - name: sampleapp-image
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
